#
# This runs after changes are merged to `master`.
#
name: Update Website
on:
  pull_request:
  workflow_dispatch:

env:
  WEB_APP_PATH: "apps/mywebsite"
  PUBLIC_WEB_DIR: "apps/mywebsite/public"
  WP_DIR_PATH: "apps/mywebsite/public/wp"
  APP_CONTENT_DIR: "apps/mywebsite/public/app"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.WEB_APP_PATH }} && ls -l -a
          mv composer.lock composer.$(date +%Y%m%d).txt && composer install
